// Generates the inventory documents from the crawl data and the build:
//   docs/url-migration.md, docs/documents-inventory.md, docs/crawl-report.md
//
//   node scripts/crawl/report-docs.mjs     (after npm run crawl and npm run build)
import fs from 'node:fs';
import path from 'node:path';
import { CACHE, ROOT, ORIGIN, readJson } from './lib.mjs';
import { localPath } from './urlmap.mjs';

const pages = readJson(path.join(CACHE, 'pages.json'), []);
const assets = readJson(path.join(CACHE, 'assets.json'), []);
const docs = readJson(path.join(CACHE, 'documents.json'), {});
const external = readJson(path.join(CACHE, 'external-links.json'), {});
const manifest = readJson(path.join(ROOT, 'dist', 'build-manifest.json'), { pages: [] });
const built = new Set(manifest.pages);
const redirects = readJson(path.join(ROOT, 'data', 'redirects.json'), []);
const known = readJson(path.join(ROOT, 'data', 'known-missing-files.json'), { files: [], links: [] });
const rel = (u) => u.replace(ORIGIN, '') || '/';
const today = new Date().toISOString().slice(0, 10);

function typeOf(p) {
  const bc = new Set((p.bodyClass || '').split(/\s+/));
  if (bc.has('home')) return 'Homepage';
  if (bc.has('single-personal')) return 'Staff profile';
  if (bc.has('single-post')) return 'News post';
  if (bc.has('page-template-default')) return 'Content page';
  if (bc.has('post-type-archive-personal')) return 'Staff archive' + (bc.has('paged') ? ' (page)' : '');
  if (bc.has('category')) return 'News category archive' + (bc.has('paged') ? ' (page)' : '');
  if (bc.has('tag')) return 'Tag archive';
  if (bc.has('author')) return 'Author archive' + (bc.has('paged') ? ' (page)' : '');
  return '—';
}
const sourceOf = (p) => {
  const t = typeOf(p);
  const u = rel(p.url);
  if (t === 'Homepage' || t === 'Content page') return u === '/' ? 'data/pages/es/home.json (site root copy)' : `data/pages/${u.split('/')[1]}/${u.split('/').filter(Boolean).pop() ?? 'home'}.json`;
  if (t === 'News post') return `data/news/${u.split('/')[1]}/${u.split('/').filter(Boolean).pop()}.json`;
  if (t === 'Staff profile') return `data/people/${u.split('/')[1]}/${u.split('/').filter(Boolean).pop()}.json`;
  return 'generated from the collections';
};

// ---------------------------------------------------------------- URL migration
{
  let md = `# URL migration\n\nGenerated by \`scripts/crawl/report-docs.mjs\` on ${today} from the crawl of ${ORIGIN} and the build manifest.\n\n`;
  md += `Every public URL found by the crawler (sitemaps + links) is listed with its static destination. Page URLs keep their exact path: \`${ORIGIN}/es/estructura/\` → \`dist/es/estructura/index.html\` (served as \`/es/estructura/\`).\n\n`;
  const rows = [];
  let preserved = 0, redirected = 0, notMigrated = 0;
  for (const p of pages.sort((a, b) => rel(a.url).localeCompare(rel(b.url)))) {
    const u = rel(p.url);
    const redirect = redirects.find((r) => r.from === u);
    let status, local, note = '', needsRedirect = 'no';
    if (p.status !== 200) {
      status = `not migrated (HTTP ${p.status} on the original)`;
      local = '—';
      note = 'Malformed link in the original content (see data/known-missing-files.json).';
      notMigrated++;
    } else if (redirect) {
      status = 'redirect';
      local = `dist${u}index.html → ${redirect.to}`;
      needsRedirect = 'yes (HTTP 301 recommended, see README "Deployment")';
      note = redirect.note;
      redirected++;
    } else if (p.finalUrl !== p.url) {
      status = 'redirect on the original';
      local = rel(p.finalUrl);
      needsRedirect = 'served by the static server (duplicate slashes are merged)';
      note = `Original redirected to ${rel(p.finalUrl)}.`;
      redirected++;
    } else if (built.has(u)) {
      status = 'preserved';
      local = `dist${u}index.html`;
      preserved++;
    } else {
      status = 'MISSING';
      local = '—';
      notMigrated++;
    }
    rows.push(`| ${u} | ${typeOf(p)} | ${local} | ${status} | ${needsRedirect} | ${note || (status === 'preserved' ? sourceOf(p) : '')} |`);
  }
  const extra = manifest.pages.filter((u) => !pages.some((p) => rel(p.url) === u));
  md += `**Summary:** ${pages.length} URLs crawled — ${preserved} preserved, ${redirected} redirects, ${notMigrated} not migrated (broken on the original).`;
  md += extra.length ? ` ${extra.length} additional pages generated: ${extra.join(', ')}.\n\n` : '\n\n';
  md += `Other URLs:\n\n- \`/404.html\` – error page (configure the server to use it, see README).\n- \`/sitemap_index.xml\` and \`/{post,page,personal,category,post_tag}-sitemap.xml\` – regenerated with the same file names as Yoast SEO.\n- \`/robots.txt\` – same rules as the original.\n- \`/es/?s=…\`, \`/en/?s=…\` – search keeps its URL (results computed in the browser, see docs/dynamic-features.md).\n- WordPress-only endpoints (\`/wp-json/\`, \`/wp-admin/\`, \`/xmlrpc.php\`, \`/feed/\`, \`/comments/feed/\`, \`/?p=<id>\` short links, oEmbed) are **not** reproduced; see docs/dynamic-features.md.\n\n`;
  md += `| Original URL | Page type | Static file | Status | Redirect needed? | Notes / content source |\n|---|---|---|---|---|---|\n${rows.join('\n')}\n`;
  fs.writeFileSync(path.join(ROOT, 'docs', 'url-migration.md'), md);
}

// ---------------------------------------------------------------- documents
{
  const DOC = /\.(pdf|docx?|xlsx?|pptx?|odt|ods|zip)(\?|#|$)/i;
  const internal = assets.filter((a) => a.isDocument || DOC.test(a.url));
  const ext = Object.entries(external).filter(([u]) => DOC.test(u));
  let md = `# Downloadable documents\n\nGenerated by \`scripts/crawl/report-docs.mjs\` on ${today}.\n\n`;
  md += `Categories: **A** hosted by the site (copied, same public URL), **B** intentionally external (linked, not copied), **C** obsolete/broken on the original, **D** generated dynamically (none found).\n\n`;
  md += `## Hosted by the original site (${internal.length})\n\n| Source URL | Local file | Referenced from | MIME type | Status | Category |\n|---|---|---|---|---|---|\n`;
  for (const a of internal.sort((x, y) => x.url.localeCompare(y.url))) {
    const lp = localPath(a.url);
    const exists = lp && fs.existsSync(path.join(ROOT, 'public', decodeURIComponent(lp)));
    const refs = (a.referencedBy || docs[a.url] || []).map(rel);
    md += `| ${rel(a.url)} | ${exists ? `public${decodeURIComponent(lp)}` : '—'} | ${refs.slice(0, 4).join('<br>')}${refs.length > 4 ? `<br>(+${refs.length - 4})` : ''} | ${a.contentType || '—'} | ${a.status === 200 ? 'copied' : `HTTP ${a.status} on the original`} | ${a.status === 200 ? 'A' : 'C'} |\n`;
  }
  const brokenLinks = known.links.filter((l) => DOC.test(l.path));
  if (brokenLinks.length) {
    md += `\nBroken document links in the original content (kept as they were):\n\n`;
    for (const l of brokenLinks) md += `- \`${l.path}\` on ${l.page} – ${l.reason}\n`;
  }
  md += `\n## External documents (${ext.length})\n\nLinked from the content and hosted by other sites (mostly the UPM course guides on www.upm.es). They remain external on purpose: they are owned and updated by other services.\n\n| URL | Referenced from | Category |\n|---|---|---|\n`;
  for (const [u, refs] of ext.sort()) md += `| ${u} | ${refs.map(rel).slice(0, 3).join('<br>')}${refs.length > 3 ? `<br>(+${refs.length - 3})` : ''} | B |\n`;
  fs.writeFileSync(path.join(ROOT, 'docs', 'documents-inventory.md'), md);
}

// ---------------------------------------------------------------- crawl report
{
  const by = (c) => assets.filter((a) => a.category === c);
  let md = `# Crawl report\n\nGenerated by \`scripts/crawl/report-docs.mjs\` on ${today}. Raw data: \`.cache/crawl/*.json\` (not committed).\n\n`;
  md += `- Pages crawled: ${pages.length} (HTML 200: ${pages.filter((p) => p.status === 200).length}); redirects: ${pages.filter((p) => p.redirects?.length).length}; errors: ${pages.filter((p) => p.status !== 200).length}\n`;
  md += `- Resources referenced: ${assets.length} — A needed: ${by('A').length}, B CMS-only: ${by('B').length}, C duplicates: ${by('C').length}, D broken/obsolete: ${by('D').length}, E external: ${by('E').length}\n`;
  md += `- External links: ${Object.keys(external).length}\n\n`;
  md += `## Redirects\n\n${pages.filter((p) => p.redirects?.length).map((p) => `- ${p.url} → ${p.finalUrl} (${p.redirects.map((r) => r.status).join(', ')})`).join('\n') || 'none'}\n\n`;
  md += `## Failed / broken resources (category D)\n\n| URL | Status | Referenced from |\n|---|---|---|\n${by('D').map((a) => `| ${a.url} | ${a.status} | ${(a.referencedBy || []).slice(0, 2).map(rel).join('<br>')} |`).join('\n')}\n\n`;
  md += `## CMS-only resources not migrated (category B)\n\n${by('B').map((a) => `- ${rel(a.url)}`).join('\n')}\n\n`;
  md += `## Intentionally external resources (category E)\n\n${by('E').map((a) => `- ${a.url}`).join('\n')}\n`;
  fs.writeFileSync(path.join(ROOT, 'docs', 'crawl-report.md'), md);
}
console.log('docs/url-migration.md, docs/documents-inventory.md, docs/crawl-report.md written');
